### ISSUE TITLE
remove repetition, generated files, embedded code copies

### ISSUE THREAD

**Issue by pabs3** [houseabsolute/File-LibMagic#17]
While looking at the magic_setparam stuff, I noticed some things that would be nice to fix from a correctness point of view:

There is some repetition in the codebase that would be nice to eliminate so that maintenance is easier. For example the MAGIC_* constants are repeated in dev-bin/regen-constants.pl, lib/File/LibMagic.pm and t/lib/Test/Exports.pm so new ones need to be added in multiple places instead of just one. In addition new constants from libmagic magic.h don't automatically show up in File::Libmagic, they have to be manually added. I'm not sure how to go about fixing these issues.

The LibreOffice source file for the PDFs is missing. My solution to this is to strip out the data from the PDF and leave the header. The data isn't used by the test suite anyway so this should be fine.

There are a number of generated files in the git repo, which means that these files will inevitably get out of date (some are already), people may forget to regenerate them, the build process might bitrot and stop working. It would be best to generate them during the build process. Files that need to be in the CPAN tarball (I guess only Makefile.PL) can be generated during the CPAN tarball build process but shouldn't be present in the git repo. The documentation may need updating to show how to build the build system.

There are a number of embedded code copies in the git repo, which means that these files will inevitably get out of date (some are already), and the build process or the File::Libmagic code might become incompatible with newer versions of them, or security issues could be discovered in them or bugs fixed in newer them. It would be best to depend on the code instead, so that folks get the latest version and that any incompatibilities are discovered early. Folks can install the code from CPAN or from their distro.

I've made a WIP patches for the last three issues:

https://github.com/pabs3/File-LibMagic/commits/correctness

See-also:

https://wiki.debian.org/UpstreamGuide
https://wiki.debian.org/EmbeddedCodeCopies

**Comment by autarch** [comment]
I think you're making too many changes without understanding why some of these things are there in the first place. Chesterton's fence and all that.

I don't want to remove any of the generated files. Checking in the generated files makes it easier for people to work with the repo without needing to install `Dist::Zilla`. The build process will not bitrot and stop working. It uses code that many other Perl authors use. Yes, the files may become out of date between releases, but they're still more useful than not.

Removing the stuff in `inc/` means the package won't even be installable when shipped, unless these were added as configure-phase dependencies. But I can't remember why I checked those in rather than simply letting them be dependencies, so I'd have to think about this change some more.

I am okay with shrinking the PDF files.

As far as the constants, one way to somewhat reduce the repetition would be to move the list of constant names to a shared module like `File::LibMagic::Constants`, which both `File/LibMagic.pm`, the test code, and `regen-constants.pl` can reference. That said I don't want to remove the checked in generated files, again to make working with the repo easier. 

What would be good would be to add a custom dzil plugin that did this constant generation so it ran every time the release ran, ensuring that the released code was always up to date. It would probably also be possible to have this extract the list of constants from the libmagic headers, but then the list depends on what version of that someone has installed on their machine, which has its own issues.

**Comment by pabs3** [comment]
I definitely don't understand why some things are the way they are.

I only use Linux distros (Debian mostly) but I assume that installing
Perl dependencies is a solved problem everywhere with CPAN, so I would
have thought that extra dependencies wouldn't be an issue.

I'm not too familiar with Dist::Zilla so I that is why I didn't add any
configure-phase dependencies, I'll look up the documentation.

I'll look at your suggested solution for the constants repetition.

I'll look at splitting the patchset up and submitting them separately
so you can merge the ones you are fine with.

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by autarch** [comment]
> I definitely don't understand why some things are the way they are. I only use Linux distros (Debian mostly) but I assume that installing Perl dependencies is a solved problem everywhere with CPAN, so I would have thought that extra dependencies wouldn't be an issue. I'm not too familiar with Dist::Zilla so I that is why I didn't add any configure-phase dependencies, I'll look up the documentation. I'll look at your suggested solution for the constants repetition. 

Configure-time deps (those needed to run the `Makefile.PL`) are a newer thing in Perl-land, which may be why I didn't take advantage of that toolchain feature for this distro. That said, I think it's okay to move to that approach now.

> I'll look at splitting the patchset up and submitting them separately so you can merge the ones you are fine with.

That would be ideal. Thanks!

**Comment by autarch** [comment]
BTW, you can test whether your changes would break the distro by running `dzil test`. This builds the distro locally, then runs its `Makefile.PL` followed by `make test`.

To install dzil and the plugins I use you'd need to do this:

```
$> cpanm install Dist::Zilla
$> cpanm $( dzil authordeps )
```

**Comment by pabs3** [comment]
BTW, re the embedded code copies in the inc/ directory, the Debian Perl
team has been working on removing them and wrote this document:

https://gobby.debian.org/export/Teams/Perl/Embedded_modules_in_inc

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by autarch** [comment]
Yeah, that makes sense. The more I think about the more I think I must've inherited this approach from an earlier maintainer of the package. It's not something I do for my own code at all. I think the CPAN modules in `inc` can be removed and replaced with configure phase deps.

**Comment by pabs3** [comment]
I've submitted everything except the removal of the generated files as
separate pull requests.

I'll work on and then submit another one for the error handling in
magic_setflags and magic_setparam once the params branch is merged.

BTW I note that `dzil test` is failing with git master, seems there are
some spelling issues (some seem to be false positives).

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by autarch** [comment]
I just released a trial version, 1.17, with all of your fixes. I'll monitor CPAN Testers and if I don't see any issues, I'll release 1.18 as a stable release in a few weeks. Thanks for your work on this!

**Comment by pabs3** [comment]
Thanks for your work on this, I look forward to the stable release.

-- 
bye,
pabs

https://wiki.debian.org/PaulWise
